Repository nemgrouplimited/symbol-desktop-wallet, pull requests merged in 2020-04, with the labels that each got.

#178 english name change and Partial sinicization #159
  src/language/en-US.json
  src/language/zh-CN.json
  src/services/WalletService.ts
  src/views/pages/accounts/import-account/wallet-selection/WalletSelectionTs.ts
Labels: changes-needed

#184 dashboard tabpanel merge #183
  src/components/MosaicBalanceList/MosaicBalanceList.less
  src/components/MosaicBalanceList/MosaicBalanceList.vue
  src/components/TableDisplay/TableDisplay.less
  src/components/TransactionList/TransactionList.less
  src/components/TransactionList/TransactionList.vue
  src/components/TransactionList/TransactionListFilters/TransactionAddressFilter/TransactionAddressFilter.less
  src/components/TransactionList/TransactionListFilters/TransactionAddressFilter/TransactionAddressFilter.vue
  src/components/TransactionList/TransactionListFilters/TransactionAddressFilter/TransactionAddressFilterTs.ts
  src/components/TransactionList/TransactionListFilters/TransactionListFilters.less
  src/components/TransactionList/TransactionListFilters/TransactionListFilters.vue
  src/components/TransactionList/TransactionListFilters/TransactionListFiltersTs.ts
  src/components/TransactionList/TransactionListFilters/TransactionStatusFilter/TransactionStatusFilter.less
  src/components/TransactionList/TransactionListFilters/TransactionStatusFilter/TransactionStatusFilter.vue
  src/components/TransactionList/TransactionListFilters/TransactionStatusFilter/TransactionStatusFilterTs.ts
  src/components/TransactionList/TransactionListTs.ts
  src/components/TransactionList/TransactionRow/TransactionRowTs.ts
  src/components/TransactionList/TransactionTable/TransactionTable.less
  src/components/TransactionList/TransactionTable/TransactionTable.vue
  src/components/TransactionList/TransactionTable/TransactionTableTs.ts
  src/components/TransactionListOptions/TransactionListOptions.vue
  src/store/Wallet.ts
  src/views/pages/dashboard/Dashboard.less
  src/views/resources/img/monitor/dash-board/dashboardUnconfirmed.png
Labels: changes-needed, enhancement, story-8

#219 the private key import times limit on the same profile(fix #214)
  src/components/WalletSelectorPanel/WalletSelectorPanelTs.ts
  src/store/Wallet.ts
  src/views/forms/FormSubWalletCreation/FormSubWalletCreationTs.ts
Labels: changes-needed

#267 Release Management
  .travis.yml
  package.json
  travis/release.sh
Labels: enhancement, ready-to-merge

#266 fixed scroll to the active wallet and some enhancements
  src/app/UIBootstrapper.ts
  src/components/MosaicBalanceList/MosaicBalanceList.less
  src/components/PeerSelector/PeerSelector.less
  src/components/PeerSelector/PeerSelector.vue
  src/components/PeerSelector/PeerSelectorTs.ts
  src/components/TableRow/TableRow.less
  src/components/TableRow/TableRow.vue
  src/components/WalletSelectorPanel/WalletSelectorPanel.vue
  src/views/pages/wallets/WalletDetailsPage/WalletDetailsPage.vue
Labels: enhancement, ready-to-merge

#269 fix the default reset on general settings "reset" button( fix #231)
  src/views/forms/FormGeneralSettings/FormGeneralSettings.vue
Labels: bug, ready-to-merge

#272 avoid the "duplicated promise" error which comes from the vue-router
  src/components/PageNavigator/PageNavigator.vue
  src/components/PageNavigator/PageNavigatorTs.ts
Labels: enhancement, under review

#283 add licence file, fixes #209
  LICENCE
Labels: enhancement, ready-to-merge

#288 review top-right icons alignment, fixes #286
  src/components/LanguageSelector/LanguageSelector.less
  src/components/WalletSelectorField/WalletSelectorField.less
  src/views/layout/PageLayout/PageLayout.common.less
  src/views/layout/PageLayout/PageLayout.vue
Labels: bug, ready-to-merge

#287 Improved signer selector in transaction table
  src/components/ActionDisplay/ActionDisplay.vue
  src/components/TransactionDetails/Transfer/Transfer.vue
  src/components/TransactionList/TransactionListFilters/TransactionAddressFilter/TransactionAddressFilter.vue
  src/components/TransactionList/TransactionListFilters/TransactionAddressFilter/TransactionAddressFilterTs.ts
  src/components/TransactionList/TransactionListFilters/TransactionListFilters.vue
  src/components/TransactionList/TransactionListFilters/TransactionListFiltersTs.ts
  src/components/TransactionList/TransactionListFilters/TransactionStatusFilter/TransactionStatusFilterTs.ts
  src/components/TransactionList/TransactionRow/TransactionRowTs.ts
  src/store/Mosaic.ts
  src/store/Namespace.ts
  src/store/Wallet.ts
Labels: bug
