Repository nemgrouplimited/symbol-desktop-wallet, pull requests merged in 2020-07, with the labels that each got.

#440 Set default qr-code on invoice
  src/components/MosaicAttachmentInput/MosaicAttachmentInputTs.ts
Labels: ready-to-merge

#447 Changed definition of transaction status
  src/core/transactions/TransactionView.ts
Labels: ready-to-merge

#427 Divisibility input optimization
  src/components/DivisibilityInput/DivisibilityInputTs.ts
Labels: ready-to-merge

#439 update Lang ja-JP
  src/language/ja-JP.json
Labels: ready-to-merge

#461 update Lang Ja
  src/language/ja-JP.json
Labels: aesthetic change, ready-to-merge

#435 Filter repeating words in Mnemonic phrase
  src/views/pages/profiles/create-profile/generate-mnemonic/GenerateMnemonicTs.ts
Labels: bugfix, ready-to-merge

#465 Fixed multisig form error on cosignatory removal (fixes #464)
  src/views/forms/FormMultisigAccountModificationTransaction/FormMultisigAccountModificationTransactionTs.ts
Labels: bugfix, ready-to-merge

#468 resetForm after transaction confirmed popup fixes #438
  src/views/forms/FormTransactionBase/FormTransactionBase.ts
Labels: bugfix, ready-to-merge

#467 fix explorer link #469
  src/components/AccountLinks/AccountLinksTs.ts
  src/components/TransactionDetails/TransactionDetailRow/TransactionDetailRow.vue
  src/components/TransactionList/TransactionRow/TransactionRow.vue
  src/components/TransactionList/TransactionRow/TransactionRowTs.ts
Labels: bugfix, ready-to-merge

#475 Faucet url enhancenment
  src/components/AccountLinks/AccountLinksTs.ts
Labels: enhancement, ready-to-merge

#462 translation fixed and number animation removed #358
  src/components/AnimatedNumber/AnimatedNumber.less
  src/components/AnimatedNumber/AnimatedNumber.vue
  src/components/AnimatedNumber/AnimatedNumberTs.ts
  src/components/NetworkStatisticsPanel/NetworkStatisticsPanel.vue
  src/components/NetworkStatisticsPanel/NetworkStatisticsPanelTs.ts
  src/language/en-US.json
  src/language/ja-JP.json
  src/language/zh-CN.json
Labels: bugfix, ready-to-merge

#481 Multisig min approval removal fix
  src/language/en-US.json
  src/language/ja-JP.json
  src/language/zh-CN.json
  src/views/forms/FormMultisigAccountModificationTransaction/FormMultisigAccountModificationTransactionTs.ts
Labels: bugfix, ready-to-merge
