Repository nemgrouplimited/symbol-desktop-wallet, pull requests merged in 2020-10, with the labels that each got.

#521 Copy button style fix
  src/components/ButtonCopyToClipboard/ButtonCopyToClipboard.vue
  src/language/en-US.json
  src/language/ja-JP.json
  src/language/zh-CN.json
  src/views/pages/profiles/import-profile/import-mnemonic/ImportMnemonic.vue
Labels: aesthetic bug, ready-to-merge

#525 Remove pkey option
  src/views/forms/FormSubAccountCreation/FormSubAccountCreation.vue
Labels: aesthetic change, ready-to-merge

#535 Add missing words to en-US. Others follow en-US.
  src/language/en-US.json
  src/language/ja-JP.json
  src/language/zh-CN.json
Labels: enhancement, ready-to-merge

#553 take action while trying to connect to a non valid network #424
  src/components/PeerSelector/PeerSelector.vue
  src/components/PeerSelector/PeerSelectorTs.ts
  src/language/en-US.json
  src/language/ja-JP.json
  src/language/zh-CN.json
  src/store/Network.ts
  src/views/layout/PageLayout/PageLayoutTs.ts
  src/views/modals/ModalNetworkNotMatchingProfile/ModalNetworkNotMatchingProfile.less
  src/views/modals/ModalNetworkNotMatchingProfile/ModalNetworkNotMatchingProfile.vue
  src/views/modals/ModalNetworkNotMatchingProfile/ModalNetworkNotMatchingProfileTs.ts
Labels: under review
